#%RAML 1.0
---

title: VAT (MTD)
version: 0.1
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

/vat:
  /{vrn}/periods/{periodKey}:
    description: Submit VAT return for period.
    uriParameters:
      vrn:
        description: Vat registration number.
        type: string
        example: "123456789"
      periodKey:
        description: Identifier for the period of the VAT return
        type: string
        example: "1234567"
    post:
      description: Submit VAT return for period.
      body:
        application/json:
          type: !include schemas/submitVatReturn.json
          example: !include examples/vatReturn.json
      responses:
        201:
          headers:
            X-CorrelationId:
              example: 5968c22d620000620096db5f
              description: Unique id for operation tracking




