#%RAML 1.0
---

title: VAT (MTD)
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: application/json

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml


documentation:
  - title: Context
    content: !include docs/context.md
  - title: Technical support
    content: !include docs/technicalSupport.md
  - title: Sandbox
    content: !include docs/sandbox.md


traits:
  contentType:
    headers:
      Content-Type:
        description: Specifies the format of the request body, which must be JSON.
        type: string
        required: true
        example: application/json
  testScenarioHeader:
    headers:
      Gov-Test-Scenario:
        description: Only in sandbox environment. See Test Data table for all header values.
        type: string
        required: false
        example: '-'


/vat:
  /{vrn}:
    uriParameters:
      vrn:
        description: VAT registration number.
        type: string
        example: "123456789"
    /obligations:
      displayName: Retrieve VAT obligations
      description: Retrieve VAT obligations
      get:
        displayName: Retrieve VAT obligations
        description: Retrieve VAT obligations
        (annotations.sandboxData): !include scenarios/vat-obligation-scenarios.md
        is: [headers.acceptHeader, contentType, testScenarioHeader]
        (annotations.scope): "read:vat"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:vat" ] } ]
        queryParameters:
         from:
           description: Obligations to return from date
           type: string
           example: 2017-01-25
           required: true
         to:
           description: Obligations to return up to date
           type: string
           example: 2017-01-25
           required: true
         status:
           description: Which obligation statuses to return (O=Open, F=Fulfilled, A=All)
           type: string
           example: A
           required: true
        responses:
          200:
            headers:
              X-CorrelationId:
                example: 5968c22d620000620096db5f
                description: Unique id for operation tracking
            body:
               application/json:
                 type: !include schemas/Obligations.json
                 example: !include examples/Obligations.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  invalidNino:
                    description: Invalid VRN
                    value:
                      code: VRN_INVALID
                  invalidDateFrom:
                    description: Invalid date from
                    value:
                      code: INVALID_DATE_FROM
                  invalidDateTo:
                    description: Invalid date to
                    value:
                      code: INVALID_DATE_TO
                  invalidDateRange:
                    description: Invalid date range
                    value:
                      code: INVALID_DATE_RANGE
                  invalidStatus:
                    description: Invalid status
                    value:
                      code: INVALID_STATUS
    /returns:
      displayName: VAT Returns
      description: Submit and read VAT returns
      /{periodKey}:
        uriParameters:
          periodKey:
            description: Period key.
            type: string
            example: "#001"
        get:
          displayName: View VAT Return
          description: Retrieve a submitted VAT return
          is: [headers.acceptHeader, contentType, testScenarioHeader]
          (annotations.scope): "write:vat"
          securedBy: [ sec.oauth_2_0: { scopes: [ "write:vat" ] } ]
          responses:
            200:
              headers:
                X-CorrelationId:
                  example: 5968c22d620000620096db5f
                  description: Unique id for operation tracking
              body:
                 application/json:
                   type: !include schemas/GetVatReturn.json
                   example: !include examples/GetVatReturn.json
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    invalidNino:
                      description: The provided VRN is invalid
                      value:
                        code: VRN_INVALID
                    periodKeyInvalid:
                      description: Invalid period key
                      value:
                        code: PERIOD_KEY_INVALID
            404:
      post:
        displayName: Submit VAT return for period
        description: Submit VAT return for period
        is: [headers.acceptHeader, contentType, testScenarioHeader]
        (annotations.scope): "write:vat"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:vat" ] } ]
        body:
          application/json:
            type: !include schemas/VatReturnDeclaration.json
            example: !include examples/VatReturnDeclaration.json
        responses:
          200:
            headers:
              X-CorrelationId:
                example: 5968c22d620000620096db5f
                description: Unique id for operation tracking
            body:
              application/json:
                type: !include schemas/VatReturnResponse.json
                example: !include examples/VatReturnResponse.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  invalidVrn:
                    description: Invalid VRN
                    value:
                      code: VRN_INVALID
                  invalidPeriodKey:
                    description: Invalid period key
                    value:
                      code: PERIOD_KEY_INVALID
                  invalidRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
                  invalidTotalValue:
                    description: totalVatDue should be equal to the sum of vatDueSales and vatDueAcquisitions
                    value:
                      code: VAT_TOTAL_VALUE
                  invalidNetValue:
                    description: netVatDue should be the difference between the largest and the smallest values among totalVatDue and vatReclaimedCurrPeriod
                    value:
                      code: VAT_NET_VALUE
                  totalValueLimit:
                    description: vatDueSales should not be greater than 20% of totalValueSalesExVAT
                    value:
                      code: VAT_DUE_SALES_LIMIT
                  vatReclaimedCurrPeriodLimit:
                    description: vatReclaimedCurrPeriod should not be greater than 20% of totalValuePurchasesExVAT
                    value:
                      code: VAT_RECLAIMED_CURR_PERIOD_LIMIT
                  invalidNumericValue:
                    description: please provide a numeric field
                    value:
                      code: INVALID_NUMERIC_VALUE
          403:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  notDeclared:
                    description: User has not declared VAT return as final
                    value:
                      code: NOT_FINALISED
                  duplicateSubmission:
                    description: User has has already submitted a VAT return for the given period
                    value:
                      code: DUPLICATE_SUBMISSION
